mandatory_proc:
  - meta
  - input_data
order_optional_proc:
  - intracone_dist
  - monteCarlo_uniform
  - monteCarlo_uniform_intracone_dist
# Processes
meta:
  process: meta_process
  variables:
    - mosaic
    - subject
    - angle
    - eccentricity
    - conetype
input_data: 
  process: input_data_process
  variables: 
    - cone_img
    - cone_coord
    - coord_unit
    - conetype_color
    - bin_width
    - dist_area_norm
    - num_mc
intracone_dist:
  process: intracone_dist_process
  variables:
    - dist
    - mean_nearest
    - std_nearest
    - hist
    - bin_edge
    - annulus_area
monteCarlo_uniform:
  process: monteCarlo_uniform_process
  variables:
    - coord
monteCarlo_uniform_intracone_dist:
  process: monteCarlo_uniform_intracone_dist_process
  dependency:
  variables:
    - dist
    - mean_nearest
    - std_nearest
    - hist
    - bin_edge
    - annulus_area
    - mean_dist_hist
    - std_dist_hist