mandatory_proc:
  - meta
  - input_data
order_optional_proc:
  - intracone_dist
  - monteCarlo_uniform
  - monteCarlo_uniform_intracone_dist
  - monteCarlo_coneLocked
  - monteCarlo_coneLocked_intracone_dist
  - norm_by_MCU_mean
# Processes
meta:
  process: meta_process
  variables:
    - mosaic
    - subject
    - angle
    - eccentricity
    - conetype
input_data: 
  process: input_data_process
  variables: 
    - cone_img
    - cone_coord
    - coord_unit
    - conetype_color
    - bin_width
    - dist_area_norm
    - num_mc
intracone_dist:
  process: intracone_dist_process
  variables:
    - dist
    - mean_nearest
    - std_nearest
    - hist
    - bin_edge
    - annulus_area
monteCarlo_uniform:
  process: monteCarlo_uniform_process
  variables:
    - coord
monteCarlo_uniform_intracone_dist:
  process: monteCarlo_uniform_intracone_dist_process
  dependency:
  variables:
    - dist
    - mean_nearest
    - std_nearest
    - hist
    - bin_edge
    - annulus_area
    - mean_hist
    - std_hist
monteCarlo_coneLocked:
  process: monteCarlo_coneLocked_process
  variables:
    - all_coord
    - coord
monteCarlo_coneLocked_intracone_dist:
  process: monteCarlo_coneLocked_intracone_dist_process
  variables: 
    - dist
    - mean_nearest
    - std_nearest
    - hist
    - bin_edge
    - annulus_area
    - mean_hist
    - std_hist
norm_by_MCU_mean:
  process: norm_by_MCU_mean_process
  variables:
    - hist
    - MCU_mean
    - MCU_std
    - MCL_mean
    - MCL_std
    - bin_edge