
# Simulation & Analysis Hierarchy
#  0) Rund default analyses on input data
#  1) Run primary analyses on input data
#  2) Generate simulated versions of input data
#  3) Run primary analyses on simulated versions
#  4) for as many additional tiers of analysis exist, 
#       run them!

# Hierarchy processes

process_hierarchy:
  process: process_hierarchy_proces
  process_type: hierarchy
  content: 
  - default_processes
  - gen_sim
  - primary_analyses
  - secondary_analyses

default_processes:
  process: default_processes_process
  process_type: hierarchy
  content: 
  - mosaic_meta
  - input_data

gen_sim: 
  process: gen_sim_process
  process_type: hierarchy

primary_analyses: # hidden process
  process: primary_analyses_process
  process_type: hierarchy

secondary_analyses: # hidden process
  process: secondary_analyses_process
  process_type: hierarchy

# Input processes

mosaic_meta:
  process: mosaic_meta_process
  process_type: input
  variables: 
    - mosaic
    - subject
    - angle
    - eccentricity
    - conetype

input_data: 
  process: input_data_process
  process_type: input
  variables: 
    - data_path
    - save_path
    - cone_img
    - cone_coord
    - coord_unit
    - conetype_color
    - sim_to_gen
    - analyses_to_run
    - bin_width
    - dist_area_norm
    - num_mc
    - num_sp
    - corr_by
    - to_be_corr
    - to_be_corr_colors
    - num_neighbors_to_average
    - std_of_blank_of_nearest_neighbor_distances

# Simulation Processes

monteCarlo_uniform: 
  process: monteCarlo_uniform_process
  process_type: simulation
  variables:
  - all_coord
  - coord

monteCarlo_coneLocked:
  process: monteCarlo_coneLocked_process
  process_type: simulation
  variables:
  - all_coord
  - coord

coneLocked_spacify_by_nearest_neighbors:
  process: coneLocked_spacify_by_nearest_neighbors_process
  process_type: simulation
  variables:
  - coord

# Primary Analysis Processes
basic_stats:
  process: basic_stats_process
  process_type: analysis
  analysis_tier: 1
  variables:
    - num_cones
    - img_area
    - density
    - hex_radius_of_this_density

intracone_dist:
  process: intracone_dist_process
  process_type: analysis
  analysis_tier: 1
  variables:
  - dist
  - mean_nearest
  - std_nearest
  - hist_mean
  - hist_std
  - bin_edge
  - annulus_area

# Secondary Analysis Processes

two_point_correlation:
  process: two_point_correlation_process
  process_type: analysis
  analysis_tier: 2
  dependencies:
  - intracone_dist
  variables:
  - all_cone_mean_nearest
  - all_cone_std_nearest
  - corred
  - maxbins
  - bin_edge
