# MosTop Inputs: analysis & simulation settings

# Paths
# -----
# load and save folder. all coordinate and image data must be in the load folder ()
# if there is already analyses for a mosaic that you want to add analyses to, it must 
# be located in the save file the same name as the coordinate file but with the save file-type
data_path:
  # - 'C:\Users\schle\Documents\GitHub\Incubator-2022-Geometry-of-Color\CSV data test locs rectgrids\'
  # - 'C:\Users\schle\Documents\GitHub\Incubator-2022-Geometry-of-Color\CSV data test locs hexgrids\'
  - 'C:\Users\schle\Documents\GitHub\Incubator-2022-Geometry-of-Color\CSV data all OCT locs Jan 2022\'
save_path:
  - 'C:\Users\schle\Documents\MosTop Outputs\experiment-12_1_voronoi_stats_1_subject\'

# settings that define the files that will be searched for in the load folder above.
# processes indicated below will be run on all such files found. 
subject:
  - ['AO001R']  # set optionis: ['AO001R', 'AO008R'] or ['test5', 'test10'] or ['rect10']
angle:
  - ['temporal']  #['temporal', 'nasal', 'superior', 'inferior']
eccentricity:
  - ['1.5']  #['1.5','3.5', '4', '4.5', '10']
conetype:
  - ['S'] #['all','L','M','S','unclassed']
conetype_color:
  - ['dodgerblue'] #['y','r','g','b','w']
coord_unit:
  - 'pixels' # units of the coordinate data loaded in - any string you want
coord_fltype:
  - '.csv'
img_fltype:
  - '.png'

# these settings only matter if convert_coorc_unit = True
convert_coord_unit: True
convert_coord_unit_to: 'arcmin'
coord_conversion_factor: 60/400 # 
density_unit: 'degrees' # 
density_conversion_factor: 3600 # applied to the converted coord unit, not the original unit

# Run settings
# ------------
# select single-mosaic processes to run. list in a....dictionary? why is it a dictionary? ***
# options: 'basic stats', 'intracone_dists', 'monteCarlo_Uniform', 'monteCarlo_coneLocked
sim_to_gen:
#  - []
 - ['monteCarlo_uniform',
    'monteCarlo_coneLocked',
    'coneLocked_spacify_by_nearest_neighbors',
    'hexgrid_by_density']
#   - ['monteCarlo_uniform',
#      'monteCarlo_coneLocked',
#  #    'coneLocked_spacify_by_nearest_neighbors',
#  #    'coneLocked_hexgrid_mask',
#      'hexgrid_by_density']

  # - ['monteCarlo_uniform',
  #    'monteCarlo_coneLocked',
  #    'coneLocked_spacify_by_nearest_neighbors',
  #    'hexgrid_by_density']
num_sim:
  - [2]

analyses_to_run:
  - ['voronoi',
     'intracone_dist']
  # - ['intracone_dist',
  #    'two_point_correlation']
 
# indicate whether all processes requested will be run on all mosaics found fitting the inputs above,
# or processes will only be run for a file if that process' outputs are not present in an identified save file
data_to_run:
  - 'all' # 'all', absent_only

# Process-specific Settings
# -------------------------

# intracone distance settings
dist_area_norm:
  - False # bool
bin_width:
  - 1

#spacify_by_nearest_neighbors settings


#hexgrid settings
sim_hexgrid_by: 'voronoi' # 'rectangular' or 'voronoi'

#two point correlation
corr_by: 'monteCarlo_uniform'
to_be_corr:
- ['measured',
   'monteCarlo_uniform']
to_be_corr_colors: # white, rebeccapurple, royalblue, darkorange, firebrick
- ['white',
   'rebeccapurple']

#plots to make
