
# Simulation & Analysis Hierarchy
#  0) Rund default analyses on input data
#  1) Run primary analyses on input data
#  2) Generate simulated versions of input data
#  3) Run primary analyses on simulated versions
#  4) for as many additional tiers of analysis exist, 
#       run them!

# Hierarchy processes

process_hierarchy:
  process: process_hierarchy_proces
  process_type: hierarchy
  content: 
  - default_processes
  - gen_sim
  - primary_analyses
  - secondary_analyses

default_processes:
  process: default_processes_process
  process_type: hierarchy

gen_sim: 
  process: gen_sim_process
  process_type: hierarchy

primary_analyses: # hidden process
  process: primary_analyses_process
  process_type: hierarchy

secondary_analyses: # hidden process
  process: secondary_analyses_process
  process_type: hierarchy

# Input processes

mosaic_meta:
  process: mosaic_meta_process
  process_type: default
  variables: 
    - mosaic
    - subject
    - angle
    - eccentricity
    - conetype

input_data: 
  process: input_data_process
  process_type: default
  variables: 
    - data_path
    - save_path
    - cone_img
    - img_x
    - img_y
    - cone_coord
    - coord_unit
    - convert_coord_unit
    - convert_coord_unit_to
    - coord_conversion_factor
    - density_unit
    - density_conversion_factor
    - conetype_color
    - sim_to_gen
    - num_sim
    - analyses_to_run
    - bin_width
    - dist_area_norm
    - corr_by
    - to_be_corr
    - to_be_corr_colors
    - sim_hexgrid_by

basic_stats:
  process: basic_stats_process
  process_type: default
  variables:
    - num_cones
    - img_area
    - rectangular_cone_density
    - hex_radius_of_this_density
    - density_unit

# Simulation Processes
# # example of a key entry for a simulation process
# simname:
#   process: simname_process # literally just the simulation's name followed by '_process'
#   process_type: simulation # flag that helps the process hierarchy find and implement the simulation 
#   variables: # any outputs of this process that need to be saved
#   - output_from_this_process_i_want_to_save
#   - another_output
#   - and_another_one

monteCarlo_uniform: 
  process: monteCarlo_uniform_process
  process_type: simulation
  variables:
  - all_coord
  - coord

monteCarlo_coneLocked:
  process: monteCarlo_coneLocked_process
  process_type: simulation
  variables:
  - all_coord
  - coord

# coneLocked_spacify_by_nearest_neighbors:
#   process: coneLocked_spacify_by_nearest_neighbors_process
#   process_type: simulation
#   variables:
#   - coord

coneLocked_maxSpacing:
  process: coneLocked_maxSpacing_process
  process_type: simulation
  variables:
  - coord
  - modded_hex_radius
  - hex_radius_decrease
  - hex_radius

hexgrid_by_density: 
  process: hexgrid_by_density_process
  process_type: simulation
  variables:
  - coord
  - num_cones_placed
  - cone_density

# Primary Analysis Processes

intracone_dist:
  process: intracone_dist_process
  process_type: analysis
  analysis_tier: 1
  variables:
  - mean_nearest
  - std_nearest
  - hist_mean
  - hist_std
  - bin_edge
  - annulus_area


voronoi:
  process: voronoi_process
  process_type: analysis
  analysis_tier: 1
  variables:
  - regions
  - vertices
  - point_region
  - bound_regions
  - bound_cones
  - voronoi_area
  - num_neighbor
  - voronoi_area_mean
  - voronoi_area_std
  - num_neighbor_mean
  - num_neighbor_std
  - neighbors_cones
  - voronoi_area_regularity
  - num_neighbor_regularity
  - density
  - hex_radius


# Secondary Analysis Processes

two_point_correlation:
  process: two_point_correlation_process
  process_type: analysis
  analysis_tier: 2
  dependencies:
  - intracone_dist
  variables:
  - all_cone_mean_nearest
  - all_cone_std_nearest
  - corred
  - maxbins
  - bin_edge

metrics_of_2PC:
  process: metrics_of_2PC_process
  process_type: analysis
  analysis_tier: 2
  dependencies:
  - two_point_correlation
  variables:
  - analysis_x_cutoff
  - M_peak
  - M_x_peak_ind
  - Sr_peak
  - Sr_x_peak_ind
  - diff_Sr_peak_from_hex_radius
  - Rr_peak
  - Rr_x_peak_ind
  - Rr_above_neg1
  - Rr_above_neg1_ind
  - Rr_cross_neg1
  - M_meets_Rr
  - M_meets_Rr_ind
  - M_cross_Rr
  - M_exclusion_radius
  - M_exclusion_area
  - Sr_meets_Rr
  - Sr_meets_Rr_ind
  - Sr_cross_Rr
  - Sr_exclusion_radius
  - Sr_exclusion_area
  - exclusion_obedience
  - relative_structure_to_max


  
