
# Simulation & Analysis Hierarchy
#  0) Rund default analyses on input data
#  1) Run primary analyses on input data
#  2) Generate simulated versions of input data
#  3) Run primary analyses on simulated versions
#  4) for as many additional tiers of analysis exist, 
#       run them!

# Hierarchy processes

process_hierarchy:
  process: process_hierarchy_proces
  process_type: hierarchy
  content: 
  - default_processes
  - gen_sim
  - run_analysis_tiers

default_processes:
  process: default_processes_process
  process_type: hierarchy

gen_sim: 
  process: gen_sim_process
  process_type: hierarchy

run_analysis_tiers:
  process: run_analysis_tiers_process
  process_type: hierarchy

primary_analyses: # hidden process
  process: primary_analyses_process
  process_type: hierarchy

secondary_analyses: # hidden process
  process: secondary_analyses_process
  process_type: hierarchy

# Input processes

mosaic_meta:
  process: mosaic_meta_process
  process_type: default
  variables: 
    - mosaic
    - subject
    - angle
    - eccentricity
    - conetype

input_data: 
  process: input_data_process
  process_type: default
  variables: 
    - data_path
    - save_path
    - cone_img
    - img_x
    - img_y
    - cone_coord
    - coord_unit
    - convert_coord_unit
    - convert_coord_unit_to
    - coord_conversion_factor
    - density_unit
    - density_conversion_factor
    - conetype_color
    - sim_to_gen
    - num_sim
    - analyses_to_run
    - bin_width
    - dist_area_norm
    - corr_by
    - to_be_corr
    - to_be_corr_colors
    - sim_hexgrid_by
    - dmin_probability_func
    - dmin_func_intercept
    - dmin_func_coef

basic_stats:
  process: basic_stats_process
  process_type: default
  variables:
    - num_cones
    - img_area
    - rectangular_cone_density
    - hex_radius_of_this_density
    - density_unit

# Simulation Processes
# # example of a key entry for a simulation process
# simname:
#   process: simname_process # literally just the simulation's name followed by '_process'
#   process_type: simulation # flag that helps the process hierarchy find and implement the simulation 
#   variables: # any outputs of this process that need to be saved
#   - output_from_this_process_i_want_to_save
#   - another_output
#   - and_another_one

monteCarlo_uniform: 
  process: monteCarlo_uniform_process
  process_type: simulation
  variables:
  - all_coord
  - coord

monteCarlo_coneLocked:
  process: monteCarlo_coneLocked_process
  process_type: simulation
  variables:
  - all_coord
  - coord

dmin:
  process: dmin_process
  process_type: simulation
  variables:
  - all_coord
  - coord
  - dmin_maxdist
  - prob_rej_type
  - intercept
  - coef

# coneLocked_spacify_by_nearest_neighbors:
#   process: coneLocked_spacify_by_nearest_neighbors_process
#   process_type: simulation
#   variables:
#   - coord

coneLocked_maxSpacing:
  process: coneLocked_maxSpacing_process
  process_type: simulation
  variables:
  - coord
  - num_cones_final
  - hex_radii_used

hexgrid_by_density: 
  process: hexgrid_by_density_process
  process_type: simulation
  variables:
  - coord
  - num_cones_final
  - hex_radii_used

# Primary Analysis Processes
intracone_dist:
  process: intracone_dist_process
  process_type: analysis
  analysis_tier: 2
  variables:
  - mean_nearest
  - std_nearest
  - hist_mean
  - hist_std
  - hist_mat
  - bin_edge
  - annulus_area
  - poisson_intervals


voronoi:
  process: voronoi_process
  process_type: analysis
  analysis_tier: 1
  variables:
  - regions
  - vertices
  - point_region
  - bound_regions
  - bound_cones
  - voronoi_area
  - voronoi_area_mean
  - voronoi_area_std
  - neighbors_cones
  - num_neighbor
  - num_neighbor_mean
  - num_neighbor_std
  - icd
  - icd_mean
  - icd_std
  - icd_regularity
  - voronoi_area_regularity
  - num_neighbor_regularity
  - density
  - hex_radius


# Secondary Analysis Processes
drp: 
  process: drp_process
  process_type: analysis
  analysis_tier: 3
  variables:
  - bin_edges
  - drp_mean
  - drp_all
  - drp_std
  - drp_ste
  - counts_per_bin
  - add_edge_correction
  - effective_radius
  - packing_factor
  - maximum_radius
  - expected_number
  - expected_drp


two_point_correlation:
  process: two_point_correlation_process
  process_type: analysis
  analysis_tier: 4
  dependencies:
  - intracone_dist
  variables:
  - corred
  - max_bins
  - max_bin_edges
  - corr_by_pi
  - corr_by_hists
  - corr_by_mean
  - corr_by_std
  - corr_by_poisson_95conf


metrics_of_2PC:
  process: metrics_of_2PC_process
  process_type: analysis
  analysis_tier: 5
  dependencies:
  - two_point_correlation
  variables:
  - analysis_x_cutoff
  - corr_by_mean
  - corr_by_pi
  - mean_corr
  - std_corr
  - dearth_bins
  - peak_bins
  - exclusion_radius
  - exclusion_factor
  - exclusion_bins
  - first_peak_rad
  - emp_max_rad

degree_structure:
  process: degree_structure_process
  process_type: analysis
  analysis_tier: 6
  metrics:
  - ['voronoi', 'voronoi_area']
  - ['voronoi', 'icd']
  - ['voronoi', 'voronoi_area_regularity']
  - ['voronoi', 'icd_regularity']
  - ['drp', 'effective_radius']
  - ['drp', 'packing_factor']
  - ['metrics_of_2PC', 'exclusion_radius']
  - ['metrics_of_2PC', 'exclusion_factor']
  variables:
  - metric
  - metric_hists
  - bin_edge
  - mos_types
  - cone_constrained_span
  - unconstrained_span
  - constraint_ratio
  - Rr_data
  - Sr_data
  - M_data
  - Dm_data
  - Q_Rr
  - Q_Sr
  - Q_Dm
  - percentiles_Rr
  - percentiles_Sr
  - percentiles_Dm
  - KS_Rr_Sr_statistic
  - KS_Rr_Sr_pval
  - KS_M_Rr_statistic
  - KS_M_Rr_pval 
  - KS_M_Sr_statistic
  - KS_M_Sr_pval
  - KS_M_Dm_statistic
  - KS_M_Dm_pval
  - degree_structure
  - DS_Q_Rr
  - DS_Q_Sr
  - DS_Q_Dm
  - DS_Rr
  - DS_Sr
  - DS_Dm


  
